---
title: "Effects of Temperature on COVID-19 Case Growth"
author: "Benjamin Buss"
output: pdf_document
---

## Abstract




## Background and Significance




## Methods

### Data

All data used in this study is publicly available, analysis was done using R version 3.6.1.

For a full description of data sources and cleaning methodology please see this document <https://github.com/BenjaminBuss/COVID19_Research/blob/master/data/README.md>.

There are 5 crucial data sets utilized in this analysis

(@) New York Times Case Counts  
(@) 2020 Daily Weather Data  
Data set is pulled from a NOAA data set that was provided courtesy of Google BigQuery.
(@) Census Data  
(@) Historical Weather Data  
30 year daily temperature normals provided by the NOAA.
(@) Geographic Area  
Land size yo

All cleaned data is hosted in [this](https://github.com/BenjaminBuss/COVID19_Research/tree/master/data) GitHub repository.

All data was transformed to a per county level, when there was multiple weather stations in a county an average of the temperatures was taken.


### Methods





$$Growth Factor = ( \prod_{n = 2}^{28} \frac{Cases_{n day}}{Cases_{n-1 day}} )^{\frac{1}{n-1}} $$


## Results




## Discussion / Conclusion




## References









## Introduction


## Data and Methods


## Results


## Discussion


## Limitations


## Acknowledgments


## References


## Tables and Figures



